grafana:
  enabled: true
  adminPassword: "nabil2407"
  service:
    type: NodePort
    nodePort: 30000
  persistence:
    enabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    retention: 2d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

nodeExporter:
  enabled: true

alertmanager:
  enabled: false