name: DevSecOps Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secret-and-config-scan:
    name: Repository Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Repository Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

  image-scan:
    name: Container Image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend Image Locally
        run: |
          docker build -t frontend:scan ./src/frontend

      - name: Run Trivy Image Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'frontend:scan'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'